'use client';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowUpRight, Plus, X } from 'lucide-react';
import { EMPTY_PRACTICAL_FACTS, type PracticalFacts, type PracticalTopic } from '@/lib/swisslaw-chat/practical';
import { PRACTICAL_REFERENCES } from '@/lib/swisslaw-chat/practical-manifest';
import { publicSourceCache } from '@/lib/swisslaw-chat/public-source-cache';
import type { HousingTopic } from '@/lib/swisslaw-chat/housing';
import { practicalGuide, type GuideParagraph } from '@/lib/swisslaw-chat/practical-content';
import { practicalText } from '@/lib/swisslaw-chat/practical-translations';
import { practicalContentText } from '@/lib/swisslaw-chat/practical-content-translations';
import { chatText } from '@/lib/swisslaw-chat/translations';
import type { Language, Source } from '@/lib/swisslaw-chat/policy';
import './swisslaw-practical-guide.css';

export default function PracticalGuide({topic, language, onDismiss}: {topic: Exclude<PracticalTopic,HousingTopic>; language: Language; onDismiss: () => void}) {
  const [facts, setFacts] = useState<PracticalFacts>({...EMPTY_PRACTICAL_FACTS});
  const [sources, setSources] = useState<Source[] | null>(null);
  const [checkedAt, setCheckedAt] = useState('');
  const [status, setStatus] = useState<'form'|'reading'|'error'|'answer'>('form');
  const [copied, setCopied] = useState(false);
  const current = useRef<{worker: Worker; timeout: ReturnType<typeof setTimeout>; revision: number} | null>(null);
  const revision = useRef(0); const heading = useRef<HTMLHeadingElement>(null);
  const p = (key:string) => practicalText(key,language);
  const c = (key:string) => practicalContentText(key,language);
  const t = (key:string) => chatText(key,language);
  const guide = practicalGuide(topic,facts);
  function stop() { revision.current++; if (current.current) {clearTimeout(current.current.timeout); current.current.worker.terminate(); current.current=null;} }
  useEffect(() => { const leave=()=>{publicSourceCache.clear();stop();setSources(null);setStatus('form');setFacts({...EMPTY_PRACTICAL_FACTS});}; window.addEventListener('pagehide',leave); return ()=>{window.removeEventListener('pagehide',leave);stop();}; },[]);
  useEffect(()=>{heading.current?.focus({preventScroll:true});},[status]);
  function change(key:keyof PracticalFacts, value:string) {stop();setSources(null);setCopied(false);setStatus('form');setFacts(previous=>({...previous,[key]:value,...(key==='role'?{regime:'unknown' as const}:{})}));}
  function read(event:FormEvent) {
    event.preventDefault(); if(current.current) return;
    stop(); setSources(null);setCopied(false); const cached=publicSourceCache.get(topic); if(cached){setSources(cached.sources);setCheckedAt(new Date(cached.checkedAt).toISOString().slice(0,10));setStatus('answer');return;} setStatus('reading'); const job=revision.current;
    let worker:Worker;
    try { worker=new Worker(new URL('../lib/swisslaw-chat/research.worker.ts',import.meta.url),{type:'module'}); } catch { setStatus('error'); return; }
    const fail=()=>{if(revision.current!==job)return;stop();setStatus('error');};
    const timeout=setTimeout(fail,75000);current.current={worker,timeout,revision:job};
    worker.onerror=fail;
    worker.onmessage=async event=>{
      if(revision.current!==job||current.current?.worker!==worker)return;
      if(event.data.type!=='sources'||!Array.isArray(event.data.sources)||event.data.sources.length!==PRACTICAL_REFERENCES[topic].length){fail();return;}
      const result=event.data.sources as Source[];
      if(result.some((s,i)=>s.id!==`${PRACTICAL_REFERENCES[topic][i].sr}:${PRACTICAL_REFERENCES[topic][i].article}`)){fail();return;}
      try { const checked=await publicSourceCache.put(topic,result); if(revision.current!==job||current.current?.worker!==worker)return; stop();setSources(checked.sources);setCheckedAt(new Date(checked.checkedAt).toISOString().slice(0,10));setStatus('answer'); } catch {fail();}
    };
    // No facts, user text or language preference are sent to this worker.
    try { worker.postMessage({practical:topic}); } catch { fail(); }
  }
  function select(key:keyof PracticalFacts,label:string,options:readonly (readonly [string,string])[]) {
    return <label className="sp-field">{p(label)}<select value={facts[key]} onChange={event=>change(key,event.target.value)}>{options.map(([value,text])=><option key={value} value={value}>{p(text)}</option>)}</select></label>;
  }
  function paragraph(item:GuideParagraph,index:number) {
    return <div key={index}><p>{c(item.text)}</p>{item.refs&&<div className="sp-citations">{item.refs.map(id=>{const source=sources?.find(s=>s.id===id);return source?<a key={id} href={source.url} target="_blank" rel="noreferrer">{source.title}<ArrowUpRight size={12} aria-hidden="true"/></a>:null;})}</div>}</div>;
  }
  async function copy() {
    const text=[p(topic==='overtime'?'Extra working hours':'Getting married'),p('Prepared guide · not generated by the model'),c(guide.intro),...guide.steps.map((s,i)=>`${i+1}. ${c(s.text)}`),...guide.rules.map(s=>c(s.text)),c(guide.check),...(sources??[]).map(s=>`${s.title}\n${s.url}`),`${p('Checked on')} ${checkedAt}`].join('\n\n');
    try{await navigator.clipboard.writeText(text);setCopied(true);}catch{setCopied(false);}
  }
  return <section className="sp-guide" id="practical-guide" aria-busy={status==='reading'}>
    <header className="sp-heading"><p className="chat-eyebrow">{p(status==='answer'?'A useful starting point':'Is this what you mean?')}</p><h1 ref={heading} tabIndex={-1}>{p(topic==='overtime'?'Extra working hours':'Getting married')}</h1></header>
    {status==='answer'&&sources?<div className="sp-answer" key="answer">
      <p className="sp-kind">{p('Prepared guide · not generated by the model')}</p><p className="sp-lead">{c(guide.intro)}</p>
      <h2>{p('Practical next steps')}</h2><ol className="sp-steps">{guide.steps.map((s,i)=><li key={i}><span aria-hidden="true">{String(i+1).padStart(2,'0')}</span>{paragraph(s,i)}</li>)}</ol>
      <aside className="sp-check"><h2>{p('What matters in your situation')}</h2><p>{c(guide.check)}</p></aside>
      {guide.rules.length>0&&<details className="sp-rules"><summary>{c('The rules behind this guide')}<Plus size={16} aria-hidden="true"/></summary>{guide.rules.map(paragraph)}</details>}
      <details className="sp-rules"><summary>{p('Read the provisions')}<Plus size={16} aria-hidden="true"/></summary>{sources.map(source=><div key={source.id}><a href={source.url} target="_blank" rel="noreferrer">{source.title}<ArrowUpRight size={13} aria-hidden="true"/></a><blockquote lang="de">{source.text}</blockquote></div>)}<p className="chat-small">{p('Checked on')} {checkedAt}. {p('The source text matches this guide’s reference version. That is not a guarantee that every applicable rule has been covered.')}</p><p className="chat-small">{p('The source provisions are in German. Translations still need independent review.')}</p></details>
      <div className="sp-actions"><button className="chat-link-button" onClick={()=>{stop();setSources(null);setStatus('form');}}>{p('Change my choices')}</button><button className="chat-link-button" onClick={copy}>{t(copied?'Copied':'Copy answer with sources')}</button></div>
    </div>:<form onSubmit={read}>
      <p className="sp-help">{p('Choose what fits. It is fine not to know yet.')}</p>
      <fieldset disabled={status==='reading'} className="sp-fields">
        {topic==='overtime'?<>
          {select('role','Your role',[['unknown','I’m not sure'],['employee','I am an employee'],['employer','I am an employer'],['self','I work for myself']])}
          {facts.role!=='self'&&<>{select('regime','Employment rules',[['unknown','I’m not sure'],['private','Private employment law'],['public','Public employment law']])}<p className="sp-field-help">{p('Check your contract. A public employer can also use a private-law contract.')}</p>{select('goal','What would help most?',[['options','Understand my options'],['less','Less extra work'],['time','Time off'],['pay','Payment']])}</>}
        </>:<>{select('location','Where do you want to marry?',[['unknown','I’m not sure'],['ch','In Switzerland'],['abroad','Outside Switzerland']])}{facts.location!=='abroad'&&select('residence','Does either of you live in Switzerland?',[['unknown','I’m not sure'],['yes','Yes'],['no','No']])}</>}
      </fieldset>
      <div className="sp-approval"><h2>{p('Legal sources')}</h2><p>{p('Sources are retrieved automatically. Only the legal terms or article references shown here go to OpenCaseLaw; your conversation stays in this tab.')}</p><div className="chat-reference-list">{PRACTICAL_REFERENCES[topic].map(ref=><a key={ref.url} href={ref.url} target="_blank" rel="noreferrer">{ref.label}</a>)}</div><button className="chat-primary" type="submit" disabled={status==='reading'}>{p(status==='reading'?'Reading the public provisions…':status==='error'?'Try again':'Read my guide')}<ArrowUpRight size={18} aria-hidden="true"/></button><p className="chat-small">{p('No model download needed for this guide.')}</p></div>
      {status==='reading'&&<div className="sp-reading" role="status"><span className="sp-reading-line" aria-hidden="true"/>{p('Reading the public provisions…')}<button type="button" aria-label={t('Stop')} onClick={()=>{stop();setStatus('form');}}><X size={18}/></button></div>}
      {status==='error'&&<p className="chat-notice" role="status">{p('These sources could not be checked. The guide has not been released. Try again or read the official information.')}</p>}
    </form>}
    <div className="sp-actions"><a href={guide.official} target="_blank" rel="noreferrer">{p('Official information')}<ArrowUpRight size={14} aria-hidden="true"/></a><button className="chat-link-button" onClick={()=>{stop();onDismiss();}}>{p(status==='answer'?'Continue with my own question':'This is about something else')}</button></div>
  </section>;
}
