/** Interface translations. Romansh and all legal-facing wording remain subject to review. */
export type Language = 'en' | 'de' | 'fr' | 'it' | 'rm';

// Entries are Swiss Standard German, French, Italian and Rumantsch Grischun.
const COPY: Record<string, readonly [string, string, string, string]> = {
  'Explain these rules on my device': ['Diese Regeln auf meinem Gerät erklären', 'Expliquer ces règles sur mon appareil', 'Spiegare queste regole sul mio dispositivo', 'Declerar questas reglas sin mes apparat'],
  'These article references will be sent to OpenCaseLaw. They may reveal your legal issue and some of your choices. Your full conversation stays in this tab.': ['Diese Artikelverweise werden an OpenCaseLaw gesendet. Daraus lassen sich Ihr rechtliches Anliegen und einzelne Ihrer Angaben ableiten. Ihr vollständiges Gespräch bleibt in diesem Tab.', 'Ces références seront envoyées à OpenCaseLaw. Elles peuvent révéler votre question juridique et certains de vos choix. Votre conversation complète reste dans cet onglet.', 'Questi riferimenti saranno inviati a OpenCaseLaw. Possono rivelare la sua questione giuridica e alcune delle sue scelte. La conversazione completa resta in questa scheda.', 'Quests renviaments vegnan tramess ad OpenCaseLaw. Els pon tradir Vossa dumonda giuridica ed intginas da Vossas tschernas. Vossa conversaziun cumpletta resta en quest tab.'],
  'What would you like to understand?': ['Was möchten Sie klären?', 'Que souhaitez-vous comprendre ?', 'Che cosa desidera chiarire?', 'Tge vulais Vus sclerir?'],
  'What would you like help with?': ['Wobei brauchen Sie Hilfe?', 'Sur quoi souhaitez-vous de l’aide ?', 'Per che cosa desidera aiuto?', 'Per tge duvrais Vus agid?'],
  'Which rules apply to your employment?': ['Welches Recht gilt für Ihr Arbeitsverhältnis?', 'Quel droit régit votre emploi ?', 'Quale diritto si applica al suo rapporto di lavoro?', 'Tge dretg vala per Vossa relaziun da lavur?'],
  'Does your contract have a fixed end date?': ['Hat Ihr Vertrag ein festes Enddatum?', 'Votre contrat a-t-il une date de fin fixée ?', 'Il suo contratto ha una data di fine prestabilita?', 'Ha Voss contract ina data da fin fixa?'],
  'Are you still in a probation period?': ['Sind Sie noch in der Probezeit?', 'Êtes-vous encore en période d’essai ?', 'È ancora nel periodo di prova?', 'Essas Vus anc en il temp d’emprova?'],
  'Start with a topic, or describe your question in your own words.': ['Wählen Sie ein Thema oder schildern Sie Ihre Frage in eigenen Worten.', 'Choisissez un sujet ou posez votre question avec vos propres mots.', 'Scelga un argomento o descriva la sua domanda con parole sue.', 'Tschernei in tema u descrivai Vossa dumonda cun Voss agens pleds.'],
  'We can start with a few facts. You can always describe your situation instead.': ['Wir beginnen mit wenigen Angaben. Sie können Ihre Situation jederzeit auch in eigenen Worten schildern.', 'Commençons par quelques précisions. Vous pouvez aussi décrire votre situation à tout moment.', 'Iniziamo con poche informazioni. Può sempre scegliere di descrivere la sua situazione con parole sue.', 'Nus cumenzain cun paucas indicaziuns. Vus pudais era descriver Vossa situaziun da tut temp cun Voss agens pleds.'],
  'Check your contract or appointment documents. A public employer can also use a private-law contract.': ['Schauen Sie in Ihren Vertrag oder Ihre Anstellungsunterlagen. Auch ein öffentlicher Arbeitgeber kann einen privatrechtlichen Vertrag abschliessen.', 'Consultez votre contrat ou vos documents d’engagement. Un employeur public peut aussi conclure un contrat de droit privé.', 'Controlli il contratto o i documenti di assunzione. Anche un datore di lavoro pubblico può stipulare un contratto di diritto privato.', 'Consultai Voss contract u Voss documents d’engaschament. Er in patrun public po far in contract da dretg privat.'],
  'You do not need to enter the date.': ['Sie müssen kein Datum eingeben.', 'Vous n’avez pas besoin de saisir la date.', 'Non occorre inserire la data.', 'Vus na stuais betg endatar la data.'],
  'Choose what your contract says. If you are unsure, that is useful to know too.': ['Orientieren Sie sich an Ihrem Vertrag. Wenn Sie unsicher sind, können Sie das ebenfalls angeben.', 'Répondez d’après votre contrat. Vous pouvez aussi indiquer que vous n’êtes pas sûr.', 'Risponda in base al suo contratto. Può anche indicare che non ne è sicuro.', 'Respundai tenor Voss contract. Vus pudais era inditgar che Vus n’essas betg segir.'],
  'Guided start': ['Geführter Einstieg', 'Parcours guidé', 'Percorso guidato', 'Cumenzament guidà'],
  'Swiss law': ['Schweizer Recht', 'Droit suisse', 'Diritto svizzero', 'Dretg svizzer'],
  'Back': ['Zurück', 'Retour', 'Indietro', 'Enavos'],
  'Your progress': ['Ihr Fortschritt', 'Votre progression', 'Il suo avanzamento', 'Voss progress'],
  'Your choices': ['Ihre Angaben', 'Vos réponses', 'Le sue risposte', 'Vossas respostas'],
  'Work': ['Arbeit', 'Travail', 'Lavoro', 'Lavur'],
  'Home': ['Wohnen', 'Logement', 'Abitazione', 'Abitar'],
  'Family': ['Familie', 'Famille', 'Famiglia', 'Famiglia'],
  'Money': ['Geld', 'Argent', 'Denaro', 'Daners'],
  'Purchases': ['Einkäufe', 'Achats', 'Acquisti', 'Cumpra'],
  'Something else': ['Etwas anderes', 'Autre chose', 'Altro', 'Insatge auter'],
  'Leaving my job': ['Meine Stelle kündigen', 'Quitter mon emploi', 'Lasciare il mio lavoro', 'Bandunar mia plazza da lavur'],
  'I want to leave my job': ['Ich möchte meine Stelle kündigen', 'Je souhaite quitter mon emploi', 'Vorrei lasciare il mio lavoro', 'Jau vuless bandunar mia plazza da lavur'],
  'I have been dismissed': ['Mir wurde gekündigt', 'J’ai été licencié', 'Ho ricevuto una disdetta dal datore di lavoro', 'Jau hai survegnì la desditga'],
  'Pay or working hours': ['Lohn oder Arbeitszeit', 'Salaire ou horaires', 'Salario o orario di lavoro', 'Salari u temp da lavur'],
  'Something else about work': ['Eine andere Frage zur Arbeit', 'Une autre question sur le travail', 'Un’altra domanda sul lavoro', 'In’autra dumonda davart la lavur'],
  'Employment rules': ['Recht für das Arbeitsverhältnis', 'Droit applicable à l’emploi', 'Diritto applicabile al rapporto di lavoro', 'Dretg applicabel a la relaziun da lavur'],
  'Private employment law': ['Privates Arbeitsrecht', 'Droit privé du travail', 'Diritto privato del lavoro', 'Dretg privat da lavur'],
  'Public employment law': ['Öffentliches Personalrecht', 'Droit public du personnel', 'Diritto pubblico del personale', 'Dretg public dal persunal'],
  'The Code of Obligations (OR/CO).': ['Das Obligationenrecht (OR).', 'Le Code des obligations (CO).', 'Il Codice delle obbligazioni (CO).', 'Il Dretg d’obligaziuns (DO).'],
  'For example, federal or cantonal personnel law.': ['Zum Beispiel das Personalrecht des Bundes oder eines Kantons.', 'Par exemple, le droit du personnel fédéral ou cantonal.', 'Per esempio, il diritto del personale federale o cantonale.', 'Per exempel il dretg dal persunal federal u chantunal.'],
  'I’m not sure': ['Ich bin nicht sicher', 'Je ne sais pas', 'Non ne sono sicuro', 'Jau na sun betg segir'],
  'No fixed end date': ['Kein festes Enddatum', 'Pas de date de fin fixée', 'Nessuna data di fine prestabilita', 'Nagina data da fin fixa'],
  'A fixed end date': ['Ein festes Enddatum', 'Une date de fin fixée', 'Una data di fine prestabilita', 'Ina data da fin fixa'],
  'Still in probation': ['Noch in der Probezeit', 'Encore en période d’essai', 'Ancora nel periodo di prova', 'Anc en il temp d’emprova'],
  'Probation has ended': ['Probezeit beendet', 'Période d’essai terminée', 'Periodo di prova terminato', 'Temp d’emprova terminà'],
  'Write in your own words': ['In eigenen Worten schildern', 'Décrire avec vos propres mots', 'Descrivere con parole proprie', 'Descriver cun agens pleds'],
  'Describe your situation instead': ['Situation in eigenen Worten schildern', 'Décrire plutôt votre situation', 'Descrivere invece la propria situazione', 'Descriver empè Vossa situaziun'],
  'Describe my situation instead': ['Meine Situation schildern', 'Décrire plutôt ma situation', 'Descrivere invece la mia situazione', 'Descriver empè mia situaziun'],
  'This path covers ordinary resignation. For immediate departure, an apprenticeship or another special arrangement, describe your situation instead.': ['Dieser Weg betrifft die ordentliche Kündigung durch Sie. Wenn Sie sofort austreten möchten, in einer Lehre sind oder eine besondere Vereinbarung haben, schildern Sie stattdessen Ihre Situation.', 'Ce parcours concerne la démission ordinaire. Pour un départ immédiat, un apprentissage ou un autre arrangement particulier, décrivez plutôt votre situation.', 'Questo percorso riguarda la disdetta ordinaria da parte sua. Per un’uscita immediata, un apprendistato o un altro accordo particolare, descriva invece la sua situazione.', 'Questa via concerna la desditga ordinaria tras Vus. Per ina partenza immediata, in emprendissadi u in’autra cunvegna speziala, descrivai empè Vossa situaziun.'],
  'A little clearer already.': ['Schon etwas klarer.', 'C’est déjà un peu plus clair.', 'Già un po’ più chiaro.', 'Gia in pau pli cler.'],
  'Read the relevant provisions': ['Relevante Bestimmungen lesen', 'Lire les dispositions pertinentes', 'Leggere le disposizioni pertinenti', 'Leger las disposiziuns relevantas'],
  'Change my choices': ['Meine Angaben ändern', 'Modifier mes réponses', 'Modificare le mie risposte', 'Midar mias respostas'],
  'These public article references will be sent to OpenCaseLaw. They can reveal the legal topic. Your answers stay in this tab.': ['Diese Verweise auf öffentliche Gesetzesartikel werden an OpenCaseLaw gesendet. Daraus kann das rechtliche Thema erkennbar sein. Ihre Antworten bleiben in diesem Tab.', 'Ces références à des articles de loi publics seront envoyées à OpenCaseLaw. Elles peuvent révéler le sujet juridique. Vos réponses restent dans cet onglet.', 'Questi riferimenti ad articoli di legge pubblici saranno inviati a OpenCaseLaw. Possono rivelare l’argomento giuridico. Le sue risposte restano in questa scheda.', 'Quests renviaments ad artitgels da lescha publics vegnan tramess ad OpenCaseLaw. Els pon revelar il tema giuridic. Vossas respostas restan en quest tab.'],
  'The provisions are in German. The local model explains them in your selected language.': ['Die Bestimmungen sind auf Deutsch. Das lokale Modell erläutert sie in Ihrer gewählten Sprache.', 'Les dispositions sont en allemand. Le modèle local les explique dans la langue choisie.', 'Le disposizioni sono in tedesco. Il modello locale le spiega nella lingua scelta.', 'Las disposiziuns èn per tudestg. Il model local las declera en la lingua tschernida.'],
  'Choose a topic or describe your situation. Guided choices work instantly on your device. You approve any public-source request before it is sent.': ['Wählen Sie ein Thema oder schildern Sie Ihre Situation. Die geführte Auswahl funktioniert sofort auf Ihrem Gerät. Jede Anfrage an öffentliche Quellen wird erst nach Ihrer Zustimmung gesendet.', 'Choisissez un sujet ou décrivez votre situation. Le parcours guidé fonctionne immédiatement sur votre appareil. Vous approuvez chaque requête vers des sources publiques avant son envoi.', 'Scelga un argomento o descriva la sua situazione. Il percorso guidato funziona subito sul suo dispositivo. Ogni richiesta a fonti pubbliche viene inviata solo dopo la sua approvazione.', 'Tschernei in tema u descrivai Vossa situaziun. La selecziun guidada funcziuna immediat sin Voss apparat. Vus approvais mintga dumonda a funtaunas publicas avant ch’ella vegn tramessa.'],
  'The guided choices use local rules. No AI, account or download is needed until you ask for an explanation.': ['Die geführte Auswahl folgt Regeln auf Ihrem Gerät. KI, Konto oder Download sind dafür nicht nötig. Erst für eine Erklärung wird das lokale Modell benötigt.', 'Le parcours guidé suit des règles sur votre appareil. Il ne nécessite ni IA, ni compte, ni téléchargement. Le modèle local est nécessaire seulement pour obtenir une explication.', 'Il percorso guidato segue regole sul suo dispositivo. Non richiede IA, un account o un download. Il modello locale serve solo quando chiede una spiegazione.', 'La selecziun guidada suonda reglas sin Voss apparat. Per quai na dovri nagina IA, nagin conto e nagin download. Il model local vegn duvrà pir per ina decleraziun.'],
  'Your conversation stays in this tab. You approve search terms or public article references before they are sent to OpenCaseLaw.': ['Ihr Gespräch bleibt in diesem Tab. Suchbegriffe oder Verweise auf öffentliche Gesetzesartikel werden erst nach Ihrer Zustimmung an OpenCaseLaw gesendet.', 'Votre conversation reste dans cet onglet. Vous approuvez les termes de recherche ou les références à des articles publics avant leur envoi à OpenCaseLaw.', 'La conversazione resta in questa scheda. I termini di ricerca o i riferimenti ad articoli pubblici vengono inviati a OpenCaseLaw solo dopo la sua approvazione.', 'Vossa conversaziun resta en quest tab. Vus approvais ils pleds da tschertga u ils renviaments ad artitgels publics avant ch’els vegnan tramess ad OpenCaseLaw.'],
  'Back to topics': ['Zurück zu den Themen', 'Retour aux sujets', 'Tornare agli argomenti', 'Enavos tar ils temas'],
};

const COLUMN: Record<Exclude<Language, 'en'>, number> = { de: 0, fr: 1, it: 2, rm: 3 };
export function guideText(value: string, language: Language): string {
  if (language === 'en') return value;
  return COPY[value]?.[COLUMN[language]] ?? value;
}
