import type { Language } from './policy';
const COPY: Record<string, [string, string, string, string]> = {
  'Possible topics': ['Mögliche Themen', 'Sujets possibles', 'Possibili argomenti', 'Temas pussaivels'],
  'Optional. Keep writing or choose a topic.': ['Optional. Schreiben Sie weiter oder wählen Sie ein Thema.', 'Facultatif. Continuez à écrire ou choisissez un sujet.', 'Facoltativo. Continui a scrivere o scelga un argomento.', 'Facultativ. Scrivai vinavant u tschernai in tema.'],
  'Suggestions stay on this device.': ['Vorschläge entstehen auf diesem Gerät.', 'Les suggestions sont calculées sur cet appareil.', 'I suggerimenti vengono elaborati su questo dispositivo.', 'Las propostas vegnan calculadas sin quest apparat.'],
  'Loading the topic model': ['Themenmodell wird geladen', 'Chargement du modèle de sujets', 'Caricamento del modello degli argomenti', 'Chargiar il model da temas'],
  'Preparing local suggestions…': ['Lokale Vorschläge werden vorbereitet…', 'Préparation des suggestions locales…', 'Preparazione dei suggerimenti locali…', 'Preparar propostas localas…'],
  'Simple word matching': ['Einfache Worterkennung', 'Reconnaissance simple de mots', 'Riconoscimento semplice di parole', 'Identificaziun simpla da pleds'],
  'Local topic model': ['Lokales Themenmodell', 'Modèle de sujets local', 'Modello locale degli argomenti', 'Model local da temas'],
  'Pause suggestions': ['Vorschläge pausieren', 'Suspendre les suggestions', 'Sospendere i suggerimenti', 'Pausar las propostas'],
  'Enable suggestions': ['Vorschläge aktivieren', 'Activer les suggestions', 'Attivare i suggerimenti', 'Activar las propostas'],
  'Try the topic model again': ['Themenmodell erneut laden', 'Réessayer le modèle de sujets', 'Riprovare il modello degli argomenti', 'Empruvar danovamain il model da temas'],
  'Remove selected topic': ['Gewähltes Thema entfernen', 'Retirer le sujet sélectionné', 'Rimuovere l’argomento selezionato', 'Allontanar il tema tschernì'],
  'The topic model is unavailable. You can keep writing and submit normally.': ['Das Themenmodell ist nicht verfügbar. Sie können weiter schreiben und Ihre Frage wie gewohnt absenden.', 'Le modèle de sujets est indisponible. Vous pouvez continuer à écrire et envoyer votre question normalement.', 'Il modello degli argomenti non è disponibile. Può continuare a scrivere e inviare la domanda normalmente.', 'Il model da temas n’è betg disponibel. Vus pudais scriver vinavant e trametter Vossa dumonda sco usità.'],
  'Data saver is on. Simple suggestions work without a download.': ['Der Datensparmodus ist aktiv. Einfache Vorschläge funktionieren ohne Download.', 'L’économiseur de données est activé. Les suggestions simples fonctionnent sans téléchargement.', 'Il risparmio dati è attivo. I suggerimenti semplici funzionano senza download.', 'Il modus da spargnar datas è activ. Propostas simplas funcziunan senza telechargiar.'],
  'Download topic model': ['Themenmodell laden', 'Télécharger le modèle de sujets', 'Scaricare il modello degli argomenti', 'Telechargiar il model da temas'],
  'Live topic suggestions use multilingual-e5-small (q8), running locally through Transformers.js 3.8.1 and ONNX Runtime on the CPU. Suggestions are optional and do not determine which law applies.': ['Live-Themenvorschläge nutzen multilingual-e5-small (q8). Das Modell läuft mit Transformers.js 3.8.1 und ONNX Runtime lokal auf der CPU. Vorschläge sind optional und entscheiden nicht, welches Recht gilt.', 'Les suggestions de sujets utilisent multilingual-e5-small (q8), exécuté localement sur le processeur avec Transformers.js 3.8.1 et ONNX Runtime. Elles sont facultatives et ne déterminent pas le droit applicable.', 'I suggerimenti usano multilingual-e5-small (q8), eseguito localmente sulla CPU con Transformers.js 3.8.1 e ONNX Runtime. Sono facoltativi e non determinano il diritto applicabile.', 'Las propostas da temas dovran multilingual-e5-small (q8), che funcziuna localmain sin la CPU cun Transformers.js 3.8.1 ed ONNX Runtime. Ellas èn facultativas e na determineschan betg il dretg applicabel.'],
  'Only public model files are downloaded. Your unfinished text is not sent to OpenCaseLaw or an AI service.': ['Es werden nur öffentliche Modelldateien geladen. Ihr noch nicht abgesendeter Text wird weder an OpenCaseLaw noch an einen KI-Dienst gesendet.', 'Seuls des fichiers publics du modèle sont téléchargés. Votre texte non envoyé n’est transmis ni à OpenCaseLaw ni à un service d’IA.', 'Vengono scaricati solo file pubblici del modello. Il testo non ancora inviato non viene trasmesso a OpenCaseLaw o a un servizio di IA.', 'I vegnan telechargiadas mo datotecas publicas dal model. Voss text anc betg tramess na vegn tramess ni ad OpenCaseLaw ni ad in servetsch d’IA.'],
  'First download': ['Erster Download', 'Premier téléchargement', 'Primo download', 'Emprima telechargiada'],
  'Use Wi-Fi. Model files can be removed below.': ['Nutzen Sie WLAN. Modelldateien lassen sich unten entfernen.', 'Utilisez le Wi-Fi. Les fichiers du modèle peuvent être supprimés ci-dessous.', 'Usi il Wi-Fi. I file del modello possono essere rimossi qui sotto.', 'Duvrai WLAN. Las datotecas dal model pon vegnir allontanadas qua sut.'],
};
export function intakeText(key: string, language: Language): string {
  return language === 'en' ? key : COPY[key]?.[{ de: 0, fr: 1, it: 2, rm: 3 }[language]] ?? key;
}
