export const seeds = [
  ['work','de','Arbeit: kündigen oder gekündigt werden, Arbeitsvertrag, Lohn, Überstunden, Ferien, Krankheit am Arbeitsplatz.'],
  ['work','de','Mein Chef zahlt mir zu wenig. Ich arbeite jeden Abend länger und weiss nicht, was ich tun soll.'],
  ['work','fr','Travail: démission, licenciement, contrat de travail, salaire impayé, heures supplémentaires et vacances.'],
  ['work','it','Lavoro: lasciare il lavoro, licenziamento, contratto, salario non pagato, straordinari e ferie.'],
  ['work','en','Employment: resigning, being fired, an employment contract, unpaid wages, overtime, holidays and sickness at work.'],
  ['work','rm','Lavur: desditga, contract da lavur, salari, uras supplementaras e vacanzas.'],
  ['home','de','Wohnen: Mietwohnung, Vermieter, Mietzins, Mieterhöhung, Wohnung kündigen, Mängel, Heizung, Schimmel und Mietkaution.'],
  ['home','de','Meine Wohnung ist kalt und feucht. Der Vermieter will nichts reparieren. Ich will ausziehen.'],
  ['home','fr','Logement: bail, locataire, propriétaire, augmentation du loyer, résiliation, chauffage en panne, moisissures et garantie de loyer.'],
  ['home','it','Abitazione: affitto, locatore, aumento della pigione, disdetta dell’appartamento, riscaldamento guasto, muffa e deposito.'],
  ['home','en','Housing: renting a home, landlord, rent increase, ending a tenancy, broken heating, mould, repairs and rental deposit.'],
  ['home','rm','Abitar: locaziun, locatari, proprietari, tschains da locaziun, desditga da l’abitaziun, stgaudament e reparaturas.'],
  ['family','de','Familie: heiraten, Ehe, Scheidung, Trennung, Kinder, Sorgerecht, Unterhalt und Erbschaft.'],
  ['family','de','Was muss ich tun, damit wir heiraten können? Wer sorgt nach unserer Trennung für unser Kind?'],
  ['family','fr','Famille: mariage, divorce, séparation, enfants, garde, autorité parentale, pension alimentaire et héritage.'],
  ['family','it','Famiglia: sposarsi, matrimonio, divorzio, separazione, figli, custodia, mantenimento ed eredità.'],
  ['family','en','Family: getting married, divorce, separation, children, custody, maintenance, inheritance and wills.'],
  ['family','rm','Famiglia: maridar, lètg, divorzi, separaziun, uffants, dretg da tgira, mantegniment ed ierta.'],
  ['money','de','Geld: Schulden, Betreibung, Zahlungsbefehl, Pfändung, Privatkredit, Bank, Versicherungen und Steuern.'],
  ['money','de','Ich kann meine Rechnungen nicht bezahlen und habe einen Zahlungsbefehl erhalten. Muss ich diese Forderung bezahlen?'],
  ['money','fr','Argent: dettes, poursuites, commandement de payer, saisie, prêt, banque, assurances et impôts.'],
  ['money','it','Denaro: debiti, esecuzione, precetto esecutivo, pignoramento, prestito, banca, assicurazioni e imposte.'],
  ['money','en','Money: debts, debt collection, payment orders, seizure, loans, banks, insurance and taxes.'],
  ['money','rm','Daners: debits, scussiun, cumond da pajament, credit, banca, assicuranzas e taglias.'],
  ['purchases','de','Einkäufe: defekte Ware, Kaufvertrag, Rückgabe, Garantie, Onlineshop, Lieferung, Abonnement und unerwünschte Rechnung.'],
  ['purchases','de','Mein gekauftes Handy funktioniert nicht. Das Geschäft will es nicht zurücknehmen oder ersetzen.'],
  ['purchases','fr','Achats: produit défectueux, contrat de vente, retour, garantie, commande en ligne, livraison et abonnement.'],
  ['purchases','it','Acquisti: prodotto difettoso, contratto di vendita, restituzione, garanzia, ordine online, consegna e abbonamento.'],
  ['purchases','en','Purchases: broken products, sales contracts, refunds, warranties, online orders, delivery and subscriptions.'],
  ['purchases','rm','Cumpra: rauba defecta, contract da cumpra, returnar rauba, garanzia, empustaziun online e furniziun.'],
  ['other','de','Andere Rechtsfragen: Polizei, Strafverfahren, Aufenthalt, Einbürgerung, Führerausweis, Nachbarn, Verein oder Unternehmen.'],
  ['other','fr','Autres questions juridiques: police, procédure pénale, permis de séjour, naturalisation, circulation, association ou entreprise.'],
  ['other','it','Altre questioni legali: polizia, procedimento penale, permesso di soggiorno, cittadinanza, circolazione, associazione o impresa.'],
  ['other','en','Other legal matters: police, criminal proceedings, residence permits, citizenship, driving, neighbours, associations and companies.'],
  ['other','rm','Autras dumondas giuridicas: polizia, procedura penala, permissiun da dimora, natiralisaziun, traffic, uniun u interpresa.'],
  ['other','de','Ich möchte ein Rezept kochen oder einen Film ansehen. Wie wird das Wetter morgen?'],
];
